init <-
function()
  {

    ## set settings
    ## -------------
    global_parm <- list(adj = 0, adj.xlab = 0, adj.ylab = 0, adj.main = 0, adj.sub = 0, bg = "transparent", cex = 0.8, cex.axis = 0.8, cex.xlab = 1, cex.ylab = 1, cex.main = 1.2, cex.sub = 0.8, col = "#000000", col.axis = "gray30", col.xlab = "gray30", col.ylab = "gray30", col.main = "gray30", col.sub = "gray30", col.box = "gray30", col.axis.ticks = "gray30", family = "", font = 1, font.axis = 1, font.xlab = 1, font.ylab = 1, font.main = 1, font.sub = 1, line.xlab = 2.5, line.ylab = 2.5, line.main = 2, line.sub = 1, lty = 1, lwd = 1, line.axis = 0.9, pch.overlap = 1 , pch.alone = 16, fontsize.point = 8, fontsize.text = 12, tcl = -0.25, panel.background.col = "transparent", reference.major.linetype = 1, reference.minor.linetype = 1, reference.major.colour = "gray40", reference.minor.colour = "gray40", reference.major.size = 0.5, reference.minor.size = 0.2, strip.background.col = gray(seq(0.8, 0.2, -0.2)), strip.border.col = "gray50", strip.text.x.size = 1, strip.text.y.size = 1, strip.text.x.colour = "gray20", strip.text.y.colour = "gray20", box.dot.pch = "|", strip.shingle.col = palette()[-1])

    ## assign the names of parameters of par (grid, ...)
    ## ---------------
    graphics_parm <- list(adj = "adj", adj.xlab = "adj.xlab", adj.ylab = "adj.ylab", adj.main = "adj.main", adj.sub = "adj.sub", bg = "bg", cex = "cex", cex.axis = "cex.axis", cex.xlab = "cex.xlab", cex.ylab = "cex.ylab", cex.main = "cex.main", cex.sub = "cex.sub", col = "col", col.axis = "col.axis", col.xlab = "col.xlab", col.ylab = "col.ylab", col.main = "col.main", col.sub = "col.sub", col.box = "notDefined", col.axis.ticks = "col.axis.ticks", family = "family", font = "font", font.axis = "font.axis", font.xlab = "font.xlab", font.ylab = "font.ylab", font.main = "font.main", font.sub = "font.sub", line.xlab = "line.xlab", line.ylab = "line.ylab", line.main = "line.main", line.sub = "line.sub", lty = "lty", lwd = "lwd", line.axis = "line.axis", pch.overlap = "pch", pch.alone = "notDefined", fontsize.point = "notDefined", fontsize.text = "ps", tcl = "tcl", panel.background.col = "notDefined", reference.major.linetype = "reference.lty", reference.minor.linetype = "notDefined", reference.major.colour = "reference.col", reference.minor.colour = "notDefined", reference.major.size = "reference.lwd", reference.minor.size = "notDefined", strip.background.col = "notDefined", strip.border.col = "notDefined", strip.text.x.size = "notDefined", strip.text.y.size = "notDefined", strip.text.x.colour = "notDefined", strip.text.y.colour = "notDefined", box.dot.pch = "notDefined", strip.shingle.col = "notDefined")

    ## assign the names of parameters of theme_set
    ## ---------------
    ggplot2_parm <- list(adj = "notDefined", adj.xlab = "notDefined", adj.ylab = "notDefined", adj.main = "notDefined", adj.sub = "notDefined", bg = "plot.background.colour", cex = "notDefined", cex.axis = c("axis.text.x.size", "axis.text.y.size"), cex.xlab = "axis.title.x.size", cex.ylab = "axis.title.y.size", cex.main = "plot.title.size", cex.sub = "notDefined", col = "notDefined", col.axis = c("axis.text.x.colour", "axis.text.y.colour"), col.xlab = "axis.title.x.colour", col.ylab = "axis.title.y.colour", col.main = "plot.title.colour", col.sub = "notDefined", col.box = "panel.border.colour", col.axis.ticks = "axis.ticks.colour", family = "base_family", font = "", font.axis = c("axis.text.x.face", "axis.text.y.face"), font.xlab = "axis.title.x.face", font.ylab = "axis.title.y.face", font.main = "plot.title.face", font.sub = "notDefined", line.xlab = "notDefined", line.ylab = "notDefined", line.main = "notDefined", line.sub = "notDefined", lty = "notDefined", lwd = "notDefined", line.axis = "notDefined", pch.overlap = "point.shape", pch.alone = "notDefined", fontsize.point = "notDefined", fontsize.text = "base_size", tcl = "axis.ticks.length", panel.background.col = "panel.background.fill", reference.major.linetype = "reference.major.linetype", reference.minor.linetype = "reference.minor.linetype", reference.major.colour = "reference.major.colour", reference.minor.colour = "reference.minor.colour", reference.major.size = "reference.major.size", reference.minor.size = "reference.minor.size", strip.background.col = "strip.background.fill", strip.border.col = "strip.background.colour", strip.text.x.size = "strip.text.x.size", strip.text.y.size = "strip.text.y.size", strip.text.x.colour = "strip.text.x.colour", strip.text.y.colour = "strip.text.y.colour", box.dot.pch = "notDefined", strip.shingle.col = "notDefined")

    ## assign the names of parameters of trellis.par.set
    ## ---------------
    lattice_parm <- list(adj = "notDefined", adj.xlab = "notDefined", adj.ylab = "notDefined", adj.main = "notDefined", adj.sub = "notDefined", bg = "background.col", cex = c("dot.symbol.cex", "plot.symbol.cex", "superpose.symbol.cex"), cex.axis = c("axis.text.cex"), cex.xlab = "par.xlab.text.cex", cex.ylab = c("par.ylab.text.cex", "par.zlab.text.cex"), cex.main = "par.main.text.cex", cex.sub = "par.sub.text.cex", col = c("add.line.col", "box.rectangle.col", "box.umbrella.col", "box.dot.col", "dot.symbol.col", "plot.line.col", "plot.symbol.col"), col.axis = "axis.text.col", col.xlab = "par.xlab.text.col", col.ylab = c("par.ylab.text.col", "par.zlab.text.col"), col.main = "par.main.text.col", col.sub = "par.sub.text.col", col.box = "notDefined", col.axis.ticks = "axis.line.col", family = "notDefined", font = "notDefined", font.axis = "axis.text.font", font.xlab = "par.xlab.text.font", font.ylab = c("par.ylab.text.font", "par.zlab.text.font"), font.main = "par.main.text.font", font.sub = "par.sub.text.font", line.xlab = "notDefined", line.ylab = "notDefined", line.main = "notDefined", line.sub = "notDefined", lty = c("add.line.lty", "box.rectangle.lty", "box.umbrella.lty", "dot.line.lty", "plot.line.lty", "plot.polygon.lty", "superpose.line.lty", "superpose.polygon.lty"), lwd = c("add.line.lwd", "plot.polygon.lwd", "box.rectangle.lwd", "box.umbrella.lwd", "dot.line.lwd", "plot.line.lwd", "superpose.line.lwd", "superpose.polygon.lwd"), line.axis = "notDefined", pch.overlap = c("plot.symbol.pch", "superpose.symbol.pch"), pch.alone = c("box.dot.pch", "dot.symbol.pch"), fontsize.point = "fontsize.point", fontsize.text = "fontsize.text", tcl = "axis.components.tck", panel.background.col = "panel.background.col", reference.major.linetype = "reference.line.lty", reference.minor.linetype = "notDefined", reference.major.colour = c("reference.line.col", "dot.line.col"), reference.minor.colour = "notDefined", reference.major.size = "reference.line.lwd", reference.minor.size = "notDefined", strip.background.col = "strip.background.col", strip.border.col = "strip.border.col", strip.text.x.size = "notDefined", strip.text.y.size = "notDefined", strip.text.x.colour = "notDefined", strip.text.y.colour = "add.text.col", box.dot.pch = "box.dot.pch", strip.shingle.col = "strip.shingle.col")

    ## return a list containing 4 lists
    temp <- list(global_parm = global_parm, graphics_parm = graphics_parm, ggplot2_parm = ggplot2_parm, lattice_parm = lattice_parm)
    return(temp)
}

